import { AuthProvider } from './context/AuthContext'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // <AuthProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    // </AuthProvider>
  )
}
